version: '3'

services:
  tortoise_gazebo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tortoise_ros1_container
    hostname: tortoise_ros1_container
    restart: "no"
    # HEADLESS GAZEBO
    #command: "bash -c 'source /root/catkin_ws/devel/setup.bash && rostest tortoisebot_waypoints waypoints_test.test'"
    # FUCKING STUPID GAZEBO, SO GIRISH IS HAPPY
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix